services:

  otel-logen:
    build:
      context: .
    restart: on-failure
    ports:
      - "9003:9003"
    volumes:
      - ./config/otel-logen.yaml:/otel-logen/config/otel-logen.yaml
    depends_on:
      collector:
        condition: service_started

  collector:
    image: otel/opentelemetry-collector-contrib:0.133.0
    restart: on-failure
    ports:
      - "13133:13133"
      - "4317:4317"
    volumes:
      - ./config/collector.yaml:/etc/otelcol-contrib/config.yaml
    environment:
      ELASTIC_ENDPOINT: ${ELASTIC_ENDPOINT}
      ELASTIC_API_KEY: ${ELASTIC_API_KEY}